# Generated by Django 5.1.4 on 2025-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ManyToManyField(blank=True, to='app.department'),
        ),
    ]
